import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const BebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "RetailSense",
  description: "Generated by create next app",
};

const navLinks = [
  { label: "Probability Graph", href: "/graph" },
  { label: "Simulator", href: "/simulator" },
  { label: "Market Trends", href: "/trends" },
  { label: "Training Configurations", href: "/config" },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-950 text-zinc-100 min-h-screen">
        <header className="border-b border-zinc-800">
          <nav className="hidden bg-navy lg:block">
            <ul className="mx-auto flex max-w-7xl items-center gap-1 px-6 text-sm font-medium text-cream/90">
              <li className="pr-10">
                <h1 className={`${BebasNeue.className} text-4xl font-bold text-red dark:text-white`}> RetailSense </h1>
              </li>
            {navLinks.map((link) => (
              <li key={link.href}>
                <Link
                  href={link.href}
                  className="
                    group
                    block
                    border-2 border-black
                    rounded-md
                    mt-4 mb-4
                    shadow-[0_10px_0_0_rgb(0,0,0)]
                    transition-shadow
                    duration-100
                    hover:shadow-[0_7px_0_0_rgb(0,0,0)]
                    active:shadow-none
                  "
                >
                  <span
                    className="
                      block
                      px-3 py-1
                      transition-transform
                      duration-100
                      group-hover:translate-y-[3px]
                      group-active:translate-y-[10px]
                    "
                  >
                    {link.label}
                  </span>
                </Link>
              </li>
            ))}
            </ul>
          </nav>
        </header>

        <main className="max-w-7xl mx-auto px-6 py-8">
          {children}
        </main>

        <footer className="border-t border-zinc-800 py-6 text-center text-zinc-400">
          © 2026 prototype by sherencrypted
        </footer>
      </body>
    </html>
  );
}
