import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RetailSense",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-950 text-zinc-100 min-h-screen">
        <header className="border-b border-zinc-800">
          <nav className="hidden bg-navy lg:block">
        <ul className="mx-auto flex max-w-7xl items-center gap-1 px-6 text-sm font-medium text-cream/90">
          <li><div className="block px-3 py-3 hover:text-gold">Probability Graph</div></li>
          <li><div className="block px-3 py-3 hover:text-gold">Monthly Analysis</div></li>
          <li><div className="block px-3 py-3 hover:text-gold">Market Trends</div></li>
          <li><div className="block px-3 py-3 hover:text-gold">Training Configurations</div></li>
          {/* navLinks.map((link) => (
            <li key={link.href}>
              <Link href={link.href} className="block px-3 py-3 hover:text-gold">
                {link.label}
              </Link>
              Logic for pulling routesm use this instead
          */}
        </ul>
      </nav>
        </header>

        <main className="max-w-7xl mx-auto px-6 py-8">
          {children}
        </main>

        <footer className="border-t border-zinc-800 py-6 text-center text-zinc-400">
          © 2026 prototype by sherencrypted
        </footer>
      </body>
    </html>
  );
}
